#!/usr/bin/env python3
"""
Phase 3 -- aggregate exp01_gap_length_activity_sweep.json into results/FINDINGS.md.

Every number in FINDINGS.md is read back from that JSON (no numbers are hand-authored here),
adapted from phase_0/make_summary.py's pattern to a single experiment instead of four.
"""
import json
import sys
from pathlib import Path

import numpy as np

RESULTS_DIR = Path(__file__).resolve().parent / "results"
JSON_PATH = RESULTS_DIR / "exp01_gap_length_activity_sweep.json"

TRAINED_MASK_LEN_MAX = 4


def load():
    if not JSON_PATH.exists():
        return None
    with open(JSON_PATH) as f:
        return json.load(f)


def fmt(x, nd=3):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "n/a"
    return f"{x:.{nd}f}"


def degradation_shape(records, metric):
    """One sentence describing how `metric` changes from mask_len=1 to the largest OOD length,
    computed from the actual values (not asserted)."""
    by_len = {r["mask_len"]: r[metric] for r in records}
    lens = sorted(by_len)
    v1, v4, vmax = by_len.get(1), by_len.get(TRAINED_MASK_LEN_MAX), by_len[lens[-1]]
    in_dist_drop = (v1 - v4) if (v1 is not None and v4 is not None) else float("nan")
    ood_drop = (v4 - vmax) if (v4 is not None and vmax is not None) else float("nan")
    monotonic = all(by_len[a] >= by_len[b] for a, b in zip(lens, lens[1:]))
    shape = "monotonically decreasing" if monotonic else "non-monotonic (noisy, not a clean decline)"
    return (
        f"{metric} is {shape} across mask_len={lens}: {fmt(v1)} at len=1 -> {fmt(v4)} at the "
        f"end of the trained range (len={TRAINED_MASK_LEN_MAX}) -> {fmt(vmax)} at len={lens[-1]} "
        f"(OOD). In-distribution drop (len 1->{TRAINED_MASK_LEN_MAX}): {fmt(in_dist_drop)}. "
        f"OOD drop (len {TRAINED_MASK_LEN_MAX}->{lens[-1]}): {fmt(ood_drop)}."
    )


def section_for_run(run_name, records):
    lines = [f"\n## {run_name}\n"]
    lines.append(
        "| band | mask_len | gap_ms | OOD | acc_top1 | si_sdr_db_gap_only | spectral_convergence_gap_only |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for r in sorted(records, key=lambda r: (r["band"], r["mask_len"])):
        ood = "**yes**" if r["ood_beyond_trained_range"] else "no"
        lines.append(
            f"| {r['band']} | {r['mask_len']} | {fmt(r['gap_ms'], 1)} | {ood} "
            f"| {fmt(r['acc_top1'])} | {fmt(r['si_sdr_db_gap_only'], 2)} "
            f"| {fmt(r['spectral_convergence_gap_only'])} |"
        )
    lines.append("")
    for band in ("high_activity", "low_activity"):
        band_records = [r for r in records if r["band"] == band]
        if not band_records:
            continue
        lines.append(f"- **{band}**, si_sdr_db_gap_only: {degradation_shape(band_records, 'si_sdr_db_gap_only')}")
    return "\n".join(lines) + "\n"


def main():
    records = load()
    report = ["# Phase 3 / Experiment 1 Findings — gap-length x activity-band sweep\n"]
    report.append(
        "Generated by `phase_3/make_summary.py` from "
        "`phase_3/results/exp01_gap_length_activity_sweep.json`. Every number below is read "
        "back from that file, not hand-authored.\n"
    )
    report.append(
        f"**Out-of-distribution caveat**: both `phase1_songs17` and `phase2_regularization` "
        f"were trained with `mask_len_max={TRAINED_MASK_LEN_MAX}` and `curriculum=false` — "
        f"neither model ever saw a gap longer than {TRAINED_MASK_LEN_MAX} frames "
        f"(~{TRAINED_MASK_LEN_MAX * 1000 / 75:.0f}ms at 75 EnCodec frames/sec) during training. "
        f"Rows marked OOD below are genuinely out-of-distribution probes, not a "
        f"same-distribution grid extension — degradation (or lack of it) at those lengths "
        f"should never be described as \"the model generalizes,\" only as an OOD probe.\n"
    )
    if not records:
        report.append("_exp01 did not run._\n")
    else:
        for run_name in sorted({r["run"] for r in records}):
            report.append(section_for_run(run_name, [r for r in records if r["run"] == run_name]))

    out_path = RESULTS_DIR / "FINDINGS.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(report))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
